### ISSUE TITLE
Test file naming inconsistency

### ISSUE THREAD

**Issue by Javran** [exercism/scheme#214] opened 2021-03-03 03:19 UTC
I noticed some inconsistencies regarding how exercise test files are named, in particular:

- under `exercises/practice/robot-name` it's `robot-name-test.scm`
- under `exercises/practice/list-ops` it's `list-ops-test.scm`
- for all other exercises, it's `test.scm`

In addition, the file content seems to be implemented differently (e.g. `xxxx-test.scm` looks simpler but doesn't have that `Well done!` message).

Is this some sort of artifact from previous repo restructure?

Background: I have a little script to help me figure how which language track I'm on and call language-specific tests accordingly for me. It'll be nice if all test files are named in a consisteny way.

**Comment by Javran** [comment] 2021-03-04 06:20
Just notice that `list-ops` and `robot-name` are not listed on the websites, so I assume those are already deprecated for Scheme track.

**Comment by guygastineau** [comment] 2022-06-09 17:59
Yes, they are, but we can revive them.  Certainly there is no need to abandon them forever ;)

**Comment by guygastineau** [comment] 2022-06-09 17:59
Since this is known though and not a bug I will close the issue.  Thank you for speaking up though,

**Closed by guygastineau** 2022-06-09 17:59 UTC
